# [[edge_functions]]
# function = "hello-world"
# path = "/hello"

# [build]
# command = "deno run --allow-net deno.ts"
# publish = "."

[build]
	command = "# no build command"
	functions = "netlify/functions"
	publish = "public"

[functions]
  node_bundler = "esbuild"